# Copyright 2021 Creu Blanca
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

from odoo import api, fields, models
from odoo.exceptions import UserError


class HrPersonalEquipment(models.Model):

    _inherit = "hr.personal.equipment"

    location_id = fields.Many2one(related="equipment_request_id.location_id")
    procurement_group_id = fields.Many2one(
        "procurement.group",
        "Procurement Group",
        readonly=True,
        help="Moves created through this stock request will be put in this "
        "procurement group. If none is given, the moves generated by "
        "procurement rules will be grouped into one big picking.",
        related="equipment_request_id.procurement_group_id",
    )
    qty_delivered = fields.Float(
        "Delivered Quantity",
        copy=False,
        compute="_compute_qty_delivered",
        compute_sudo=True,
        store=True,
    )
    move_ids = fields.One2many(
        "stock.move", "personal_equipment_id", string="Stock Moves"
    )
    skip_procurement = fields.Boolean(compute="_compute_skip_procurement")
    lot_ids = fields.Many2many(
        "stock.lot", compute="_compute_lot_ids", string="Serial Numbers"
    )

    @api.depends("state", "product_id", "product_id.type")
    def _compute_skip_procurement(self):
        for record in self:
            record.skip_procurement = record._skip_procurement()

    @api.depends(
        "move_ids.state",
        "move_ids.scrapped",
        "move_ids.product_uom_qty",
        "move_ids.product_uom",
        "equipment_request_id.picking_ids.move_ids.scrapped",
    )
    def _compute_qty_delivered(self):
        for line in self:
            qty = 0.0
            if line.product_id.tracking == "none" and len(line.move_ids.lot_ids) == 0:
                move_ids_to_be_processed = (
                    line.equipment_request_id.picking_ids.filtered(
                        lambda x: x.state != "done"
                    ).move_ids
                )
                move_ids = line.move_ids.filtered(
                    lambda x: x.product_id == line.product_id
                    and x.quantity_done
                    and not x.origin_returned_move_id
                )
                returned_move_ids = line.move_ids.filtered(
                    lambda x: x.product_id == line.product_id
                    and x.quantity_done
                    and x.origin_returned_move_id
                ).sorted("create_date")
                scrapped_move_ids = (
                    line.equipment_request_id.picking_ids.move_ids.filtered(
                        lambda x: x.scrapped
                    )
                ).sorted("create_date")
                move_ids = move_ids - scrapped_move_ids
                if move_ids:
                    if len(move_ids) == 1 and (
                        not returned_move_ids and not scrapped_move_ids
                    ):
                        line.qty_delivered = move_ids.quantity_done
                    # check for duplication moves and use latest one
                    elif len(move_ids) > 1 and (
                        returned_move_ids and not scrapped_move_ids
                    ):
                        move_ids = move_ids.sorted("create_date")
                        line.qty_delivered = move_ids[-1].quantity_done
                    else:
                        if returned_move_ids:
                            returned_move_ids = returned_move_ids.sorted("create_date")
                            if not move_ids_to_be_processed or (
                                move_ids_to_be_processed
                                and (returned_move_ids in move_ids_to_be_processed)
                            ):
                                line.qty_delivered = (
                                    line.qty_delivered
                                    - returned_move_ids[-1].quantity_done
                                )
                            elif scrapped_move_ids:
                                if scrapped_move_ids in move_ids_to_be_processed:
                                    line.qty_delivered = (
                                        line.qty_delivered
                                        - scrapped_move_ids[-1].quantity_done
                                    )
                continue
            # Filter scrapped move_ids
            scrapped_lot_ids = line.equipment_request_id.picking_ids.move_ids.filtered(
                lambda x: x.scrapped
            ).lot_ids
            if scrapped_lot_ids:
                line.lot_ids = line.lot_ids.filtered(
                    lambda x: x not in scrapped_lot_ids
                )
            lot_ids_qty_info = {
                lot_id.id: self.env["stock.quant"]._get_available_quantity(
                    line.product_id,
                    line.location_id,
                    lot_id,
                )
                for lot_id in line.lot_ids
            }
            # Filter moves which are moved to PPE location
            moves_to_be_checked = line.move_ids.filtered(
                lambda r: r.state == "done"
                and line.product_id == r.product_id
                and r.location_dest_id == line.location_id
                and not r.origin_returned_move_id
                and r.lot_ids not in scrapped_lot_ids
            )
            # check and remove moves with same lots
            # if same lots exists among filtered moves
            lots_to_be_filtered = self.env["stock.move"]
            for lot in moves_to_be_checked.mapped("lot_ids"):
                move_with_same_lots = moves_to_be_checked.filtered(
                    lambda x: lot in x.lot_ids
                )
                if len(move_with_same_lots) > 1:
                    lot_records = move_with_same_lots.sorted("create_date")
                    lots_to_be_filtered |= lot_records[:-1]
            moves_to_be_checked -= lots_to_be_filtered
            for move in moves_to_be_checked:
                qty += sum([lot_ids_qty_info.get(lot.id, 0) for lot in move.lot_ids])
            line.qty_delivered = qty

    @api.depends(
        "move_ids.lot_ids",
    )
    def _compute_lot_ids(self):
        for line in self:
            available_lot_ids = {}
            returned_move_ids = line.move_ids.filtered(
                lambda x: x.product_id == line.product_id
                and x.quantity_done
                and x.origin_returned_move_id
            )
            moves_to_be_checked = line.move_ids - returned_move_ids
            for move_id in moves_to_be_checked:
                if move_id.lot_ids:
                    lot_infos = self.env["stock.quant"].read_group(
                        domain=[
                            ("product_id", "=", line.product_id.id),
                            ("location_id", "child_of", line.location_id.id),
                            ("lot_id", "in", move_id.lot_ids.ids),
                        ],
                        fields=["lot_id", "quantity: sum"],
                        groupby=["lot_id"],
                    )
                    available_lot_ids.update(
                        {
                            lot_info["lot_id"][0]: lot_info["quantity"]
                            for lot_info in lot_infos
                            if lot_info["lot_id"]
                            and lot_info["quantity"] not in (0.0, -1.0)
                        }
                    )
            lot_ids = available_lot_ids.keys()
            if lot_ids:
                returned_lots = returned_move_ids.mapped("lot_ids")
                actual_move_lots = moves_to_be_checked.mapped("lot_ids")
                # Remove returned lots from available lots in location
                # when same lot_id  used in different PPE request
                if len(returned_move_ids) and (
                    len(returned_lots) != len(actual_move_lots)
                ):
                    lot_ids = [
                        x
                        for x in available_lot_ids.keys()
                        if x not in returned_move_ids.mapped("lot_ids").ids
                    ]
                line.lot_ids = [(6, 0, lot_ids)]
            else:
                line.lot_ids = False

    def _skip_procurement(self):
        return self.product_id.type not in ("consu", "product")

    def _prepare_procurement_values(self, group_id=False):

        """Prepare specific key for moves or other components that
        will be created from a procurement rule
        coming from a stock request. This method could be override
        in order to add other custom key that could be used in
        move/po creation.
        """
        return {
            "group_id": group_id or self.procurement_group_id.id or False,
            "partner_id": self.employee_id.user_id.partner_id.id,
            "personal_equipment_id": self.id,
        }

    def _get_company(self):
        return self.employee_id.company_id or self.env.company

    def _action_launch_procurement_rule(self):
        """
        Launch procurement group run method with required/custom
        fields generated by a
        equipment request. procurement group will launch '_run_move',
        '_run_buy' or '_run_manufacture'
        depending on the stock request product rule.
        """
        errors = []
        for allocation in self:
            if allocation.skip_procurement:
                continue

            values = allocation._prepare_procurement_values(
                group_id=allocation.procurement_group_id
            )
            try:
                # We launch with sudo because potentially we could create
                # objects that the user is not authorized to create, such
                # as PO.
                procurement = self.env["procurement.group"].Procurement(
                    allocation.product_id,
                    allocation.quantity,
                    allocation.product_uom_id,
                    allocation.location_id,
                    allocation.equipment_request_id.name,
                    allocation.equipment_request_id.name,
                    allocation._get_company(),
                    values,
                )
                self.env["procurement.group"].sudo().run([procurement])
            except UserError as error:
                errors.append(error.args[0])
        if errors:
            raise UserError("\n".join(errors))
        return True

    def _accept_request(self):
        res = super()._accept_request()
        self._action_launch_procurement_rule()
        return res

    def _validate_allocation_vals(self):
        res = super()._validate_allocation_vals()
        if self.skip_procurement:
            res["qty_delivered"] = self.quantity
        return res
